type EnergyConstantsType = {
  DEFAULT_SHOWER_LENGTH_IN_MINUTES: number;
  DEFAULT_SHOWER_VOLUME_IN_LITERS_PER_MINUTE: number;
  DEFAULT_SHOWER_POWER_CONSUMPTION_PER_LITER_IN_KWH: number;
};

export const ENERGY_CONSTANTS: EnergyConstantsType = {
  DEFAULT_SHOWER_LENGTH_IN_MINUTES: 10,
  DEFAULT_SHOWER_VOLUME_IN_LITERS_PER_MINUTE: 16,
  DEFAULT_SHOWER_POWER_CONSUMPTION_PER_LITER_IN_KWH: 0.035
};
